baseURL = "http://example.org/"
languageCode = "en-us"
title = "PiFunc"
theme = "arvtheme"


[params]
    author = "Ashish R Vidyarthi"
    #authorImage = "/images/arv.jpg"
    showcardimage = false

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/ashishrv"
    pre = "<i class='fab fa-github'></i>"


[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/arvidyarthi"
    pre = "<i class='fab fa-twitter'></i>"


[[menu.footer]]
  name = "About"
  url = "/about"
